### ISSUE TITLE
Missing keybinds

### ISSUE THREAD

**Issue by a-beyblade** [Garklein/surviv-timings#3]
All relevant surviv.io keybinds should be supported, with the same semantics.

- `primary.bind` (default 1)
- `secondary.bind` (2)
- `melee.bind` (3)
- -> **`stow` (E)** <- (does same as melee)
- `throwable.bind` (4)
- `attack` (Left Mouse)
- `equipOtherGun` (Space)
- -> **`equipLastGun` (Q)** <-
- `equipPreviousWeapon` (Mouse Wheel Up)
- `equipNextWeapon` (Mouse Wheel Down)
- -> **`switchWeaponSlots` (T)** <-

**Comment by Garklein** [comment]
Added.
